server:
    port: 8084
spring:
    application:
        name: order-service

    datasource:
        url: ${ORDER_DATABASE_URL_LOCAL}
        username: ${DATABASE_USERNAME_LOCAL}
        password: ${DATABASE_PASSWORD_LOCAL}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate

    flyway:
        enabled: true
        locations: classpath:db/migration
        validate-on-migrate: false
        baseline-on-migrate: true
    
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}

app:
  upload:
    dir: ${UPLOAD_DIR:uploads}
    url: ${UPLOAD_URL:http://localhost:8084/uploads}

logging:
  level:
    io.github.Huduong123.order_service.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.core.env: TRACE


eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL}
    instance:
        hostname: ${EUREKA_INSTANCE_HOSTNAME}
aws:
    region: ${AWS_REGION}
    s3:
        bucket-name: ${AWS_S3_BUCKET_NAME}
    credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}