server:
    port: 8083
spring:
    application:
        name: cart-service

    datasource:
        url: ${CART_DATABASE_URL_LOCAL}
        username: ${DATABASE_USERNAME_LOCAL}
        password: ${DATABASE_PASSWORD_LOCAL}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: validate

    flyway:
        enabled: true
        locations: classpath:db/migration
        validate-on-migrate: false
        baseline-on-migrate: true
    
    servlet:
        multipart:
            max-file-size: 5MB
            max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET}

app:
  upload:
    dir: ${UPLOAD_DIR:uploads}
    url: ${UPLOAD_URL:http://localhost:8083/uploads}

logging:
  level:
    io.github.Huduong123.cart_service.security: DEBUG
    org.springframework.security: DEBUG
    org.springframework.core.env: TRACE


eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_SERVER_URL}
    instance:
        hostname: ${EUREKA_INSTANCE_HOSTNAME}

kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
        group-id: cart-service-group
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        properties:
            spring.json.trusted.packages: "io.github.Huduong123.cart_service.events.dto"
    topic:
        order-events: order-events